if(NOT CMAKE_CROSSCOMPILING)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_DBUS dbus-1)
endif()

set_extra_dirs_lib(DBUS dbus)
find_library(DBUS_LIBRARY
  NAMES dbus-1
  HINTS ${HINTS_DBUS_LIBDIR} ${PC_DBUS_LIBDIR} ${PC_DBUS_LIBRARY_DIRS}
  PATHS ${PATHS_DBUS_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
set_extra_dirs_include(DBUS dbus "${DBUS_LIBRARY}")
find_path(DBUS_INCLUDEDIR dbus/dbus.h
  HINTS ${HINTS_DBUS_INCLUDEDIR} ${PC_DBUS_INCLUDEDIR} ${PC_DBUS_INCLUDE_DIRS}
  PATHS ${PATHS_DBUS_INCLUDEDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DBus DEFAULT_MSG DBUS_LIBRARY DBUS_INCLUDEDIR)

mark_as_advanced(DBUS_LIBRARY DBUS_INCLUDEDIR)

if(DBus_FOUND)
  set(DBUS_LIBRARIES ${DBUS_LIBRARY})
  set(DBUS_INCLUDE_DIRS ${DBUS_INCLUDEDIR})
  if(DEFINED PC_DBUS_INCLUDE_DIRS AND PC_DBUS_INCLUDE_DIRS)
    list(APPEND DBUS_INCLUDE_DIRS ${PC_DBUS_INCLUDE_DIRS})
    list(REMOVE_DUPLICATES DBUS_INCLUDE_DIRS)
  endif()
endif()
