if(NOT CMAKE_CROSSCOMPILING)
  find_package(PkgConfig QUIET)
  if(PKG_CONFIG_FOUND)
    pkg_check_modules(PC_PULSEAUDIO libpulse-simple)
  endif()
endif()

set_extra_dirs_lib(PULSEAUDIO pulse)
find_library(PULSEAUDIO_LIBRARY
  NAMES pulse
  HINTS ${HINTS_PULSEAUDIO_LIBDIR} ${PC_PULSEAUDIO_LIBDIR} ${PC_PULSEAUDIO_LIBRARY_DIRS}
  PATHS ${PATHS_PULSEAUDIO_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
find_library(PULSEAUDIO_SIMPLE_LIBRARY
  NAMES pulse-simple
  HINTS ${HINTS_PULSEAUDIO_LIBDIR} ${PC_PULSEAUDIO_LIBDIR} ${PC_PULSEAUDIO_LIBRARY_DIRS}
  PATHS ${PATHS_PULSEAUDIO_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
set_extra_dirs_include(PULSEAUDIO pulse "${PULSEAUDIO_LIBRARY}")
find_path(PULSEAUDIO_INCLUDEDIR pulse/pulseaudio.h
  HINTS ${HINTS_PULSEAUDIO_INCLUDEDIR} ${PC_PULSEAUDIO_INCLUDEDIR} ${PC_PULSEAUDIO_INCLUDE_DIRS}
  PATHS ${PATHS_PULSEAUDIO_INCLUDEDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PulseAudio DEFAULT_MSG PULSEAUDIO_LIBRARY PULSEAUDIO_SIMPLE_LIBRARY PULSEAUDIO_INCLUDEDIR)

mark_as_advanced(PULSEAUDIO_LIBRARY PULSEAUDIO_SIMPLE_LIBRARY PULSEAUDIO_INCLUDEDIR)

if(PulseAudio_FOUND)
  set(PULSEAUDIO_LIBRARIES ${PULSEAUDIO_LIBRARY} ${PULSEAUDIO_SIMPLE_LIBRARY})
  list(REMOVE_DUPLICATES PULSEAUDIO_LIBRARIES)
  set(PULSEAUDIO_INCLUDE_DIRS ${PULSEAUDIO_INCLUDEDIR})
  if(DEFINED PC_PULSEAUDIO_INCLUDE_DIRS AND PC_PULSEAUDIO_INCLUDE_DIRS)
    list(APPEND PULSEAUDIO_INCLUDE_DIRS ${PC_PULSEAUDIO_INCLUDE_DIRS})
    list(REMOVE_DUPLICATES PULSEAUDIO_INCLUDE_DIRS)
  endif()
endif()
